[program:attendance_service]
command=/root/.venv/bin/python check_attendance.py
directory=/app/backend
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/attendance.err.log
stdout_logfile=/var/log/supervisor/attendance.out.log
stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true
